### ISSUE TITLE
add healthz endpoint for liveness probing

### ISSUE THREAD

**Issue by Kariton** [nekomeowww/factorio-rcon-api#1]
Hey,

i just added your container to my helm chart for kubernetes deployments.
ill create a PR late to add it to the upstream helm chart here: [SQLJames/factorio-server-charts](https://github.com/SQLJames/factorio-server-charts)
for liveness checks it is really useful to have probing endpoints like `/healthz` as described here:

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

**Comment by nekomeowww** [comment]
Ah, thanks, I will integrate them ASAP I finish my travel (2 days left)

**Comment by Kariton** [comment]
PR: https://github.com/SQLJames/factorio-server-charts/pull/57

**Comment by nekomeowww** [comment]
Released https://github.com/nekomeowww/factorio-rcon-api/releases/tag/v1.1.0
