### ISSUE TITLE
direct integration of swagger-ui

### ISSUE THREAD

**Issue by Kariton** [nekomeowww/factorio-rcon-api#3]
can you ship the container with an installed (optionally enabled) swagger interface?
this way it can also be used as quick command interface by utilizing the `Try it out` feature directly

**Comment by nekomeowww** [comment]
Ok, it is possible. Will do it once I finish my travel (2 days left)

**Comment by nekomeowww** [comment]
Added, and deployed to https://factorio-rcon-api.ayaka.io/apis/docs, or you can navigate to http://localhost:24180/apis/docs to view it.

**Comment by nekomeowww** [comment]
Released https://github.com/nekomeowww/factorio-rcon-api/releases/tag/v1.1.0
