### ISSUE TITLE
[v2] Factorio Evolution lists only one planet

### ISSUE THREAD

**Issue by Kariton** [nekomeowww/factorio-rcon-api#4]
```sh
curl -X GET http://factorio/api/v2/factorio/console/command/evolution
{"evolutionFactor":0.9406,"time":11,"pollution":83,"spawnerKills":6,"planetName":"Nauvis"}
```

in game i can get evolution for our 4 planets and additionally those from mod surfaces. (blueprint-sandboxes)

**Comment by nekomeowww** [comment]
> in game i can get evolution for our 4 planets and additionally those from mod surfaces. (blueprint-sandboxes)

Really?

Can you provide me an example of ingame output? I haven't made my progress that far so I didn't think that much.

**Comment by Kariton** [comment]
```sh
# curl -X POST https://factorio/api/v2/factorio/console/command/raw -H "Content-Type: application/json" -d '{ "input": "/evolution"}'
{"output":"Nauvis - Evolution factor: 0.9495. (Time 10%) (Pollution 84%) (Spawner kills 5%)\nbpsb-lab-p-Kynazori - Evolution factor: 0.6358. (Time 100%) (Pollution 0%) (Spawner kills 0%)\nbpsb-lab-f-player - Evolution factor: 0.6672. (Time 87%) (Pollution 13%) (Spawner kills 0%)\nbpsb-lab-p-Kunstduenger - Evolution factor: 0.6355. (Time 100%) (Pollution 0%) (Spawner kills 0%)\nbpsb-lab-p-Daemon16 - Evolution factor: 0.6036. (Time 100%) (Pollution 0%) (Spawner kills 0%)\nVulcanus - Evolution factor: 0.5852. (Time 100%) (Pollution 0%) (Spawner kills 0%)\nGleba - Evolution factor: 0.6436. (Time 65%) (Pollution 16%) (Spawner kills 19%)\nFulgora - Evolution factor: 0.5347. (Time 100%) (Pollution 0%) (Spawner kills 0%)\n\n"}
```

**Comment by nekomeowww** [comment]
Thanks, will add this to unit test.

And, besides all of these, would you like to be invited to work on this project with me? Since you are so kindly to respond and open up issues here and helping me to improve this project, I would like to offer you an invitation here as collaborator to together maintain this project.

**Comment by Kariton** [comment]
thank you for that kind and thoughtful offer.

some time in the feature i want to use this api as interface (maybe bidirectional) for alerting and chat stuff
but i'm more of a python scripting guy, despite the fact that i would like to learn go, i have a lot of other projects. 
nevertheless this could be the right opportunity for me to get started. :)

i can help you manage issues or try to recreate certain reported bugs.
but everything related to the codebase is currently beyond my capabilities.

**Comment by nekomeowww** [comment]
> in game i can get evolution for our 4 planets and additionally those from mod surfaces. (blueprint-sandboxes)

Fixed, released.
